"""Generate README.md from the curated LLM-gateways registry."""

from __future__ import annotations

from collections import defaultdict

from __version__ import __version__
from data import TOOLS, Category, Tool


def _badge(label: str, message: str, color: str) -> str:
    label = label.replace(" ", "%20")
    message = str(message).replace(" ", "%20").replace("-", "--")
    return f"![{label}](https://img.shields.io/badge/{label}-{message}-{color})"


def _source(t: Tool) -> str:
    if t.open_source:
        return "🟢 OSS"
    if t.license != "Proprietary":
        return "🔃 Source-available"
    return "🔒 Proprietary"


def _row(t: Tool) -> str:
    name = f"[{t.name}]({t.url})" if t.url else t.name
    return f"| {name} | {t.org} | {_source(t)} | {t.license} | {t.note} |"


def generate() -> str:
    total = len(TOOLS)
    oss = sum(1 for t in TOOLS if t.open_source)
    categories = sorted({t.category for t in TOOLS}, key=lambda c: c.label)

    by_cat: dict[Category, list[Tool]] = defaultdict(list)
    for t in TOOLS:
        by_cat[t.category].append(t)

    out: list[str] = []
    out.append("<!-- AUTO-GENERATED by report.py — run `python main.py generate` to refresh. -->")
    out.append("# 🚦 LLM Gateways & Routers Directory\n")
    out.append(" ".join([
        _badge("version", __version__, "blue"),
        _badge("tools", total, "green"),
        _badge("open%20source", oss, "brightgreen"),
        _badge("categories", len(categories), "purple"),
        "[![CI](https://github.com/Amarel-Taylor-Scott/llm-gateways-routers-directory/actions/workflows/ci.yml/badge.svg)]"
        "(https://github.com/Amarel-Taylor-Scott/llm-gateways-routers-directory/actions/workflows/ci.yml)",
        "[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](LICENSE)",
    ]))
    out.append("")
    out.append("> A curated, machine-readable directory of **LLM gateways, proxies & routers** — "
               "the layer that gives your app one unified API with routing, fallbacks, retries, "
               "caching, rate-limiting, and cost control across many model providers.\n")
    out.append("Distinct from the inference engines that *serve* models and from raw provider "
               "endpoints: these *route and manage* calls across providers. Ships a small CLI to "
               "search/filter/export. Nothing is vendored here.\n")

    out.append("## Quick start\n")
    out.append("```bash")
    out.append("pip install -e .                 # stdlib-only; no runtime deps")
    out.append("gateway-dir list                 # list all")
    out.append("gateway-dir list --open-source   # only OSS gateways")
    out.append("gateway-dir search router        # search name/org/note/tags")
    out.append("gateway-dir export --format csv > gateways.csv")
    out.append("gateway-dir generate             # regenerate this README")
    out.append("```\n")

    out.append("## At a glance\n")
    out.append(f"- **{total}** tools across **{len(categories)}** categories")
    out.append(f"- 🟢 **{oss}** open source · 🔒 **{total - oss}** proprietary / hosted\n")

    out.append("## Directory\n")
    for cat in sorted(by_cat, key=lambda c: c.label):
        tools = sorted(by_cat[cat], key=lambda t: t.name.lower())
        out.append(f"### {cat.label} ({len(tools)})\n")
        out.append("| Tool | Org | Source | License | Notes |")
        out.append("|------|-----|--------|---------|-------|")
        out.extend(_row(t) for t in tools)
        out.append("")

    out.append("## Choosing one (rules of thumb)\n")
    out.append("- **Self-host an OpenAI-compatible proxy:** LiteLLM, One API, Portkey Gateway.")
    out.append("- **Route to cut cost:** RouteLLM.")
    out.append("- **Don't run infra (hosted):** OpenRouter, Eden AI, Cloudflare AI Gateway.")
    out.append("- **Already on an API gateway:** Kong AI Gateway.\n")

    out.append("## Legend\n")
    out.append("🟢 open source (license shown) · 🔃 source-available · 🔒 proprietary / hosted.\n")

    out.append("## Contributing\n")
    out.append("Add or correct an entry in [`data.py`](data.py), run `python main.py generate`, "
               "and open a PR. See [CONTRIBUTING.md](CONTRIBUTING.md) and "
               "[CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md). Keep the focus on gateways/routers "
               "(not inference engines or raw endpoints); record the EXACT license; omit anything "
               "you can't verify.\n")

    out.append("## License\n")
    out.append("[MIT](LICENSE) © Amarel Taylor Scott. Catalog metadata only; each tool's own "
               "license/terms govern its use.\n")
    return "\n".join(out)


if __name__ == "__main__":
    print(generate())
